# Generated by Django 4.2 on 2023-04-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
